blank_issues_enabled: true
contact_links:
  - name: ðŸ’¬ Discussions
    url: https://github.com/mrmcmullan/flycatcher/discussions
    about: Ask questions and discuss ideas with the community
  - name: ðŸ“– Documentation
    url: https://mrmcmullan.github.io/flycatcher
    about: Read the documentation
